package blackjack

import blackjack.model.cards.Card
import blackjack.model.cards.Rank
import blackjack.model.cards.Suit

val ACE_CLUBS = Card(Rank.ACE, Suit.CLUBS)
val TWO_CLUBS = Card(Rank.TWO, Suit.CLUBS)
val THREE_CLUBS = Card(Rank.THREE, Suit.CLUBS)
val FOUR_CLUBS = Card(Rank.FOUR, Suit.CLUBS)
val FIVE_CLUBS = Card(Rank.FIVE, Suit.CLUBS)
val SIX_CLUBS = Card(Rank.SIX, Suit.CLUBS)
val SEVEN_CLUBS = Card(Rank.SEVEN, Suit.CLUBS)
val EIGHT_CLUBS = Card(Rank.EIGHT, Suit.CLUBS)
val NINE_CLUBS = Card(Rank.NINE, Suit.CLUBS)
val TEN_CLUBS = Card(Rank.TEN, Suit.CLUBS)
val JACK_CLUBS = Card(Rank.JACK, Suit.CLUBS)
val QUEEN_CLUBS = Card(Rank.QUEEN, Suit.CLUBS)
val KING_CLUBS = Card(Rank.KING, Suit.CLUBS)

val ACE_DIAMONDS = Card(Rank.ACE, Suit.DIAMONDS)
val TWO_DIAMONDS = Card(Rank.TWO, Suit.DIAMONDS)
val THREE_DIAMONDS = Card(Rank.THREE, Suit.DIAMONDS)
val FOUR_DIAMONDS = Card(Rank.FOUR, Suit.DIAMONDS)
val FIVE_DIAMONDS = Card(Rank.FIVE, Suit.DIAMONDS)
val SIX_DIAMONDS = Card(Rank.SIX, Suit.DIAMONDS)
val SEVEN_DIAMONDS = Card(Rank.SEVEN, Suit.DIAMONDS)
val EIGHT_DIAMONDS = Card(Rank.EIGHT, Suit.DIAMONDS)
val NINE_DIAMONDS = Card(Rank.NINE, Suit.DIAMONDS)
val TEN_DIAMONDS = Card(Rank.TEN, Suit.DIAMONDS)
val JACK_DIAMONDS = Card(Rank.JACK, Suit.DIAMONDS)
val QUEEN_DIAMONDS = Card(Rank.QUEEN, Suit.DIAMONDS)
val KING_DIAMONDS = Card(Rank.KING, Suit.DIAMONDS)

val ACE_HEARTS = Card(Rank.ACE, Suit.HEARTS)
val TWO_HEARTS = Card(Rank.TWO, Suit.HEARTS)
val THREE_HEARTS = Card(Rank.THREE, Suit.HEARTS)
val FOUR_HEARTS = Card(Rank.FOUR, Suit.HEARTS)
val FIVE_HEARTS = Card(Rank.FIVE, Suit.HEARTS)
val SIX_HEARTS = Card(Rank.SIX, Suit.HEARTS)
val SEVEN_HEARTS = Card(Rank.SEVEN, Suit.HEARTS)
val EIGHT_HEARTS = Card(Rank.EIGHT, Suit.HEARTS)
val NINE_HEARTS = Card(Rank.NINE, Suit.HEARTS)
val TEN_HEARTS = Card(Rank.TEN, Suit.HEARTS)
val JACK_HEARTS = Card(Rank.JACK, Suit.HEARTS)
val QUEEN_HEARTS = Card(Rank.QUEEN, Suit.HEARTS)
val KING_HEARTS = Card(Rank.KING, Suit.HEARTS)

val ACE_SPADES = Card(Rank.ACE, Suit.SPADES)
val TWO_SPADES = Card(Rank.TWO, Suit.SPADES)
val THREE_SPADES = Card(Rank.THREE, Suit.SPADES)
val FOUR_SPADES = Card(Rank.FOUR, Suit.SPADES)
val FIVE_SPADES = Card(Rank.FIVE, Suit.SPADES)
val SIX_SPADES = Card(Rank.SIX, Suit.SPADES)
val SEVEN_SPADES = Card(Rank.SEVEN, Suit.SPADES)
val EIGHT_SPADES = Card(Rank.EIGHT, Suit.SPADES)
val NINE_SPADES = Card(Rank.NINE, Suit.SPADES)
val TEN_SPADES = Card(Rank.TEN, Suit.SPADES)
val JACK_SPADES = Card(Rank.JACK, Suit.SPADES)
val QUEEN_SPADES = Card(Rank.QUEEN, Suit.SPADES)
val KING_SPADES = Card(Rank.KING, Suit.SPADES)
